[package]
name = "ethereum-consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
displaydoc = { version = "0.2", default-features = false }
sha2 = { version = "0.10.2", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["alloc", "serde"] }

milagro_bls = { git = "https://github.com/datachainlab/milagro_bls", rev = "bc2b5b5e8d48b7e2e1bfaa56dc2d93e13cb32095", default-features = false }
ssz-rs = { git = "https://github.com/bluele/ssz_rs", branch = "serde-no-std", default-features = false, features = ["serde"] }
ssz-rs-derive = { git = "https://github.com/bluele/ssz_rs", branch = "serde-no-std", default-features = false }
rs_merkle = { version = "1.2.0", default-features = false }
primitive-types = { version = "0.12.1", default-features = false }

[dev-dependencies]
serde_json = "1.0.91"

[features]
default = ["std"]
std = []
