name: test
on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - Cargo.toml
      - Cargo.lock
      - ci/**
      - crates/**
  push:
    branches: main
    paths:
      - .github/workflows/test.yml
      - Cargo.toml
      - Cargo.lock
      - ci/**
      - crates/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make lint
      - run: cargo test
      - run: cargo build --bin ethlc
